{-# LANGUAGE DataKinds #-}
{-# LANGUAGE NumericUnderscores #-}

module Opcodes(Opcode(..)) where
import Clash.Prelude

data Opcode 
  = FmaddDot                -- page PAGE
  | FmaddsDot               -- page 157
  | FmsubDot                -- page 157
  | FmsubsDot               -- page 158
  | FnmaddDot               -- page 158
  | FnmaddsDot              -- page 158
  | FnmsubDot               -- page 158
  | FnmsubsDot              -- page 158
  | DaddDot                 -- page 158
  | DcffixDot               -- page 193
  | DctdpDot                -- page 215
  | DctfixDot               -- page 213
  | DctfixqDot              -- page 215
  | DdivDot                 -- page 215
  | DenbcdDot               -- page 196
  | DmulDot                 -- page 217
  | DquaDot                 -- page 195
  | DquaiDot                -- page 204
  | DrintnDot               -- page 203
  | DrintxDot               -- page 211
  | DrrndDot                -- page 209
  | DrspDot                 -- page 206
  | DsubDot                 -- page 214
  | FaddDot                 -- page 193
  | FaddsDot                -- page 152
  | FcfidDot                -- page 152
  | FcfidsDot               -- page 163
  | FcfiduDot               -- page 164
  | FcfidusDot              -- page 164
  | FctidDot                -- page 165
  | FctiduDot               -- page 159
  | FctiduzDot              -- page 160
  | FctidzDot               -- page 161
  | FctiwDot                -- page 160
  | FctiwuDot               -- page 161
  | FctiwuzDot              -- page 162
  | FctiwzDot               -- page 163
  | FdivDot                 -- page 162
  | FdivsDot                -- page 153
  | FmulDot                 -- page 153
  | FreDot                  -- page 153
  | FresDot                 -- page 154
  | FrimDot                 -- page 154
  | FrinDot                 -- page 166
  | FripDot                 -- page 166
  | FrizDot                 -- page 166
  | FrspDot                 -- page 166
  | FrsqrteDot              -- page 159
  | FrsqrtesDot             -- page 155
  | FsqrtDot                -- page 155
  | FsqrtsDot               -- page 154
  | FsubDot                 -- page 154
  | FsubsDot                -- page 152
  | DaddqDot                -- page 152
  | DdivqDot                -- page 193
  | DmulqDot                -- page 196
  | DsubqDot                -- page 195
  | DquaqDot                -- page 193
  | DcffixqDot              -- page 204
  | DctqpqDot               -- page 215
  | DenbcdqDot              -- page 213
  | DquaiqDot               -- page 217
  | DrdpqDot                -- page 203
  | DrintnqDot              -- page 214
  | DrintxqDot              -- page 211
  | DrrndqDot               -- page 209
  | TbeginDot               -- page 206
  | TabortdcDot             -- page 890
  | TabortwcDot             -- page 894
  | TabortDot               -- page 893
  | TabortdciDot            -- page 892
  | TabortwciDot            -- page 894
  | TreclaimDot             -- page 893
  | Sc                      -- page 969
  | Scv                     -- page 42
  | Mtspr                   -- page 42
  | Dcmpoq                  -- page 117 974
  | Dcmpuq                  -- page 199
  | Dtstexq                 -- page 198
  | Stfdpx                  -- page 201
  | XsaddqpFlagO            -- page 149
  | Xscmpeqdp               -- page 520
  | Xscmpgedp               -- page 524
  | Xscmpgtdp               -- page 525
  | Xscmpoqp                -- page 526
  | XsdivqpFlagO            -- page 529
  | Xsmaddadp               -- page 564
  | Xsmaddasp               -- page 570
  | Xsmaddmdp               -- page 573
  | Xsmaddmsp               -- page 570
  | Xsmaxcdp                -- page 573
  | Xsmaxjdp                -- page 581
  | Xsmincdp                -- page 583
  | Xsminjdp                -- page 587
  | Xsmsubadp               -- page 589
  | Xsmsubasp               -- page 591
  | Xsmsubmdp               -- page 594
  | Xsmsubmsp               -- page 591
  | XsmulqpFlagO            -- page 594
  | Xsnmaddadp              -- page 602
  | Xsnmaddasp              -- page 608
  | Xsnmaddmdp              -- page 613
  | Xsnmaddmsp              -- page 608
  | Xsnmsubadp              -- page 613
  | Xsnmsubasp              -- page 619
  | Xsnmsubmdp              -- page 622
  | Xsnmsubmsp              -- page 619
  | XssubqpFlagO            -- page 622
  | Xvmaddadp               -- page 647
  | Xvmaddasp               -- page 701
  | Xvmaddmsp               -- page 704
  | Xvmsubadp               -- page 704
  | Xvmsubasp               -- page 715
  | Xvmsubmdp               -- page 718
  | Xvnmaddadp              -- page 715
  | Xvnmaddasp              -- page 727
  | Xvnmaddmdp              -- page 732
  | Xvnmaddmsp              -- page 727
  | Xvnmsubadp              -- page 732
  | Xvnmsubasp              -- page 735
  | Xvnmsubmdp              -- page 738
  | Xvnmsubmsp              -- page 735
  | StqcxDot                -- page 738
  | Slbieg                  -- page 872
  | Tlbie                   -- page 1025
  | XsmaddqpFlagO           -- page 1034
  | XsmsubqpFlagO           -- page 576
  | XsnmaddqpFlagO          -- page 597
  | XsnmsubqpFlagO          -- page 616
  | Stxsdx                  -- page 625
  | Stxsibx                 -- page 498
  | Stxsihx                 -- page 499
  | Stxsiwx                 -- page 499
  | Stxsspx                 -- page 500
  | Stxvb16x                -- page 502
  | Stxvd2x                 -- page 503
  | Stxvh8x                 -- page 504
  | Stxvl                   -- page 505
  | Stxvll                  -- page 507
  | Stxvw4x                 -- page 509
  | Stxvx                   -- page 506
  | Vaddecuq                -- page 510
  | Vaddeuqm                -- page 273
  | Vperm                   -- page 273
  | Vpermr                  -- page 260
  | Vsel                    -- page 260
  | Vsubecuq                -- page 261
  | Vsubeuqm                -- page 279
  | Xxperm                  -- page 279
  | Xxpermr                 -- page 772
  | Xxsel                   -- page 772
  | StbcxDot                -- page 773
  | StdcxDot                -- page 866
  | SthcxDot                -- page 869
  | Stswx                   -- page 867
  | StwcxDot                -- page 65
  | AddFlagODot             -- page 868
  | AddcFlagODot            -- page 69
  | AddeFlagODot            -- page 70
  | Addex                   -- page 71
  | Addg6s                  -- page 72
  | Addi                    -- page 111
  | Addic                   -- page 67
  | AddicDot                -- page 69
  | Addis                   -- page 69
  | AddmeFlagODot           -- page 67
  | Addpcis                 -- page 71
  | AddzeFlagODot           -- page 68
  | AndDot                  -- page 72
  | AndcDot                 -- page 94
  | AndiDot                 -- page 95
  | AndisDot                -- page 92
  | BFlagLinkFlagAbosolute  -- page 92
  | BcFlagLinkFlagAbosolute -- page 37
  | BcctrFlagLink           -- page 37
  | BcdaddDot               -- page 38
  | BcdcfnDot               -- page 348
  | BcdcfsqDot              -- page 350
  | BcdcfzDot               -- page 354
  | BcdcpsgnDot             -- page 351
  | BcdctnDot               -- page 356
  | BcdctsqDot              -- page 352
  | BcdctzDot               -- page 354
  | BcdsDot                 -- page 353
  | BcdsetsgnDot            -- page 357
  | BcdsrDot                -- page 356
  | BcdsubDot               -- page 359
  | BcdtruncDot             -- page 348
  | BcdusDot                -- page 360
  | BcdutruncDot            -- page 358
  | BclrFlagLink            -- page 361
  | BctarFlagLink           -- page 38
  | Bpermd                  -- page 39
  | Cbcdtd                  -- page 100
  | Cdtbcd                  -- page 111
  | Clrbhrb                 -- page 111
  | Cmp                     -- page 909
  | Cmpb                    -- page 85
  | Cmpeqb                  -- page 97
  | Cmpi                    -- page 88
  | Cmpl                    -- page 85
  | Cmpli                   -- page 86
  | Cmprb                   -- page 86
  | CntlzdDot               -- page 87
  | CntlzwDot               -- page 99
  | CnttzdDot               -- page 96
  | CnttzwDot               -- page 99
  | Copy                    -- page 96
  | Cpabort                 -- page 855
  | Crand                   -- page 856
  | Crandc                  -- page 40
  | Creqv                   -- page 41
  | Crnand                  -- page 41
  | Crnor                   -- page 40
  | Cror                    -- page 41
  | Crorc                   -- page 40
  | Crxor                   -- page 41
  | Darn                    -- page 40
  | Dcbf                    -- page 78
  | Dcbst                   -- page 852
  | Dcbt                    -- page 851
  | Dcbtst                  -- page 849
  | Dcbz                    -- page 850
  | Dcmpo                   -- page 851
  | Dcmpu                   -- page 199
  | DdedpdDot               -- page 198
  | DdedpdqDot              -- page 217
  | DiexDot                 -- page 217
  | DiexqDot                -- page 218
  | DivdFlagODot            -- page 218
  | DivdeFlagODot           -- page 81
  | DivdeuFlagODot          -- page 82
  | DivduFlagODot           -- page 82
  | DivwFlagODot            -- page 81
  | DivweFlagODot           -- page 74
  | DivweuFlagODot          -- page 75
  | DivwuFlagODot           -- page 75
  | DscliDot                -- page 74
  | DscliqDot               -- page 220
  | DscriDot                -- page 220
  | DscriqDot               -- page 220
  | Dtstdc                  -- page 220
  | Dtstdcq                 -- page 200
  | Dtstdg                  -- page 200
  | Dtstdgq                 -- page 200
  | Dtstex                  -- page 200
  | Dtstsf                  -- page 201
  | Dtstsfi                 -- page 202
  | Dtstsfiq                -- page 202
  | Dtstsfq                 -- page 202
  | DxexDot                 -- page 202
  | DxexqDot                -- page 218
  | Eieio                   -- page 218
  | EqvDot                  -- page 875
  | ExtsbDot                -- page 95
  | ExtshDot                -- page 96
  | ExtswDot                -- page 96
  | ExtswsliDot             -- page 99
  | FabsDot                 -- page 110
  | Fcmpo                   -- page 150
  | Fcmpu                   -- page 167
  | FcpsgnDot               -- page 167
  | FmrDot                  -- page 150
  | Fmrgew                  -- page 150
  | Fmrgow                  -- page 151
  | FmulsDot                -- page 151
  | FnabsDot                -- page 153
  | FnegDot                 -- page 150
  | FselDot                 -- page 150
  | Ftdiv                   -- page 168
  | Ftsqrt                  -- page 156
  | Hrfid                   -- page 156
  | Icbi                    -- page 956
  | Icbt                    -- page 840
  | Isel                    -- page 840
  | Isync                   -- page 91
  | Lbarx                   -- page 863
  | Lbz                     -- page 864
  | Lbzcix                  -- page 48
  | Lbzu                    -- page 966
  | Lbzux                   -- page 48
  | Lbzx                    -- page 48
  | Ld                      -- page 48
  | Ldarx                   -- page 53
  | Ldat                    -- page 869
  | Ldbrx                   -- page 860
  | Ldcix                   -- page 61
  | Ldu                     -- page 966
  | Ldux                    -- page 53
  | Ldx                     -- page 53
  | Lfd                     -- page 53
  | Lfdp                    -- page 142
  | Lfdpx                   -- page 149
  | Lfdu                    -- page 149
  | Lfdux                   -- page 142
  | Lfdx                    -- page 143
  | Lfiwax                  -- page 142
  | Lfiwzx                  -- page 143
  | Lfs                     -- page 143
  | Lfsu                    -- page 140
  | Lfsux                   -- page 141
  | Lfsx                    -- page 142
  | Lha                     -- page 141
  | Lharx                   -- page 50
  | Lhau                    -- page 865
  | Lhaux                   -- page 50
  | Lhax                    -- page 50
  | Lhbrx                   -- page 50
  | Lhz                     -- page 60
  | Lhzcix                  -- page 49
  | Lhzu                    -- page 966
  | Lhzux                   -- page 49
  | Lhzx                    -- page 49
  | Lmw                     -- page 49
  | Lq                      -- page 62
  | Lqarx                   -- page 58
  | Lswi                    -- page 871
  | Lswx                    -- page 64
  | Lvebx                   -- page 64
  | Lvehx                   -- page 242
  | Lvewx                   -- page 242
  | Lvsl                    -- page 243
  | Lvsr                    -- page 247
  | Lvx                     -- page 247
  | Lvxl                    -- page 243
  | Lwa                     -- page 243
  | Lwarx                   -- page 52
  | Lwat                    -- page 865
  | Lwaux                   -- page 860
  | Lwax                    -- page 52
  | Lwbrx                   -- page 52
  | Lwz                     -- page 60
  | Lwzcix                  -- page 51
  | Lwzu                    -- page 966
  | Lwzux                   -- page 51
  | Lwzx                    -- page 51
  | Lxsd                    -- page 51
  | Lxsdx                   -- page 480
  | Lxsibzx                 -- page 480
  | Lxsihzx                 -- page 482
  | Lxsiwax                 -- page 482
  | Lxsiwzx                 -- page 483
  | Lxssp                   -- page 484
  | Lxsspx                  -- page 485
  | Lxv                     -- page 485
  | Lxvb16x                 -- page 492
  | Lxvd2x                  -- page 487
  | Lxvdsx                  -- page 488
  | Lxvh8x                  -- page 494
  | Lxvl                    -- page 495
  | Lxvll                   -- page 489
  | Lxvw4x                  -- page 491
  | Lxvwsx                  -- page 496
  | Lxvx                    -- page 497
  | Maddhd                  -- page 492
  | Maddhdu                 -- page 80
  | Maddld                  -- page 80
  | Mcrf                    -- page 80
  | Mcrfs                   -- page 41
  | Mcrxrx                  -- page 171
  | Mfbhrbe                 -- page 120
  | Mfcr                    -- page 909
  | MffsDot                 -- page 122
  | Mffscdrn                -- page 170
  | Mffscdrni               -- page 170
  | Mffsce                  -- page 170
  | Mffscrn                 -- page 170
  | Mffscrni                -- page 170
  | Mffsl                   -- page 170
  | Mfmsr                   -- page 170
  | Mfocrf                  -- page 979
  | Mfspr                   -- page 122
  | Mftb                    -- page 119 975
  | Mfvscr                  -- page 898
  | Mfvsrd                  -- page 362
  | Mfvsrld                 -- page 112
  | Mfvsrwz                 -- page 112
  | Modsd                   -- page 113
  | Modsw                   -- page 83
  | Modud                   -- page 77
  | Moduw                   -- page 83
  | Msgclr                  -- page 77
  | Msgclrp                 -- page 1130
  | Msgsnd                  -- page 1132
  | Msgsndp                 -- page 1129
  | Msgsync                 -- page 1131
  | Mtcrf                   -- page 1132
  | Mtfsb0Dot               -- page 121
  | Mtfsb1Dot               -- page 173
  | MtfsfDot                -- page 173
  | MtfsfiDot               -- page 172
  | Mtmsr                   -- page 172
  | Mtmsrd                  -- page 977
  | Mtocrf                  -- page 978
  | Mtvscr                  -- page 121
  | Mtvsrd                  -- page 362
  | Mtvsrdd                 -- page 114
  | Mtvsrwa                 -- page 115
  | Mtvsrws                 -- page 114
  | Mtvsrwz                 -- page 116
  | MulhdDot                -- page 115
  | MulhduDot               -- page 79
  | MulhwDot                -- page 79
  | MulhwuDot               -- page 73
  | MulldFlagODot           -- page 73
  | Mulli                   -- page 79
  | MullwFlagODot           -- page 73
  | NandDot                 -- page 73
  | NegFlagODot             -- page 94
  | NorDot                  -- page 72
  | OrDot                   -- page 95
  | OrcDot                  -- page 94
  | Ori                     -- page 95
  | Oris                    -- page 92
  | PasteDot                -- page 93
  | Popcntb                 -- page 855
  | Popcntd                 -- page 97
  | Popcntw                 -- page 99
  | Prtyd                   -- page 97
  | Prtyw                   -- page 98
  | Rfebb                   -- page 98
  | Rfid                    -- page 905
  | Rfscv                   -- page 955
  | RldclDot                -- page 953
  | RldcrDot                -- page 104
  | RldicDot                -- page 104
  | RldiclDot               -- page 105
  | RldicrDot               -- page 105
  | RldimiDot               -- page 106
  | RlwimiDot               -- page 106
  | RlwinmDot               -- page 103
  | RlwnmDot                -- page 102
  | Setb                    -- page 103
  | SlbfeeDot               -- page 122
  | Slbia                   -- page 1031
  | Slbiag                  -- page 1026
  | Slbie                   -- page 1028
  | Slbmfee                 -- page 1024
  | Slbmfev                 -- page 1031
  | Slbmte                  -- page 1030
  | Slbsync                 -- page 1029
  | SldDot                  -- page 1032
  | SlwDot                  -- page 109
  | SradDot                 -- page 107
  | SradiDot                -- page 110
  | SrawDot                 -- page 110
  | SrawiDot                -- page 108
  | SrdDot                  -- page 108
  | SrwDot                  -- page 109
  | Stb                     -- page 107
  | Stbcix                  -- page 54
  | Stbu                    -- page 967
  | Stbux                   -- page 54
  | Stbx                    -- page 54
  | Std                     -- page 54
  | Stdat                   -- page 57
  | Stdbrx                  -- page 862
  | Stdcix                  -- page 61
  | Stdu                    -- page 967
  | Stdux                   -- page 57
  | Stdx                    -- page 57
  | Stfd                    -- page 57
  | Stfdp                   -- page 146
  | Stfdu                   -- page 149
  | Stfdux                  -- page 146
  | Stfdx                   -- page 146
  | Stfiwx                  -- page 146
  | Stfs                    -- page 147
  | Stfsu                   -- page 145
  | Stfsux                  -- page 145
  | Stfsx                   -- page 145
  | Sth                     -- page 145
  | Sthbrx                  -- page 55
  | Sthcix                  -- page 60
  | Sthu                    -- page 967
  | Sthux                   -- page 55
  | Sthx                    -- page 55
  | Stmw                    -- page 55
  | Stop                    -- page 62
  | Stq                     -- page 958
  | Stswi                   -- page 59
  | Stvebx                  -- page 65
  | Stvehx                  -- page 245
  | Stvewx                  -- page 245
  | Stvx                    -- page 246
  | Stvxl                   -- page 246
  | Stw                     -- page 246
  | Stwat                   -- page 56
  | Stwbrx                  -- page 862
  | Stwcix                  -- page 60
  | Stwu                    -- page 967
  | Stwux                   -- page 56
  | Stwx                    -- page 56
  | Stxsd                   -- page 56
  | Stxssp                  -- page 498
  | Stxv                    -- page 501
  | SubfFlagODot            -- page 507
  | SubfcFlagODot           -- page 69
  | SubfeFlagODot           -- page 70
  | Subfic                  -- page 71
  | SubfmeFlagODot          -- page 70
  | SubfzeFlagODot          -- page 71
  | Sync                    -- page 72
  | Tcheck                  -- page 873
  | Td                      -- page 895
  | Tdi                     -- page 91
  | TendDot                 -- page 91
  | Tlbiel                  -- page 891
  | Tlbsync                 -- page 1038
  | TrechkptDot             -- page 1042
  | TsrDot                  -- page 970
  | Tw                      -- page 895
  | Twi                     -- page 90
  | Vabsdub                 -- page 90
  | Vabsduh                 -- page 297
  | Vabsduw                 -- page 297
  | Vaddcuq                 -- page 298
  | Vaddcuw                 -- page 273
  | Vaddfp                  -- page 269
  | Vaddsbs                 -- page 321
  | Vaddshs                 -- page 269
  | Vaddsws                 -- page 269
  | Vaddubm                 -- page 270
  | Vaddubs                 -- page 270
  | Vaddudm                 -- page 272
  | Vadduhm                 -- page 270
  | Vadduhs                 -- page 271
  | Vadduqm                 -- page 272
  | Vadduwm                 -- page 273
  | Vadduws                 -- page 271
  | Vand                    -- page 272
  | Vandc                   -- page 312
  | Vavgsb                  -- page 312
  | Vavgsh                  -- page 295
  | Vavgsw                  -- page 295
  | Vavgub                  -- page 295
  | Vavguh                  -- page 296
  | Vavguw                  -- page 296
  | Vbpermd                 -- page 296
  | Vbpermq                 -- page 346
  | Vcfsx                   -- page 346
  | Vcfux                   -- page 325
  | Vcipher                 -- page 325
  | Vcipherlast             -- page 333
  | Vclzb                   -- page 333
  | Vclzd                   -- page 340
  | Vclzh                   -- page 340
  | Vclzlsbb                -- page 340
  | Vclzw                   -- page 342
  | VcmpbfpDot              -- page 340
  | VcmpeqfpDot             -- page 328
  | VcmpequbDot             -- page 329
  | VcmpequdDot             -- page 303
  | VcmpequhDot             -- page 304
  | VcmpequwDot             -- page 303
  | VcmpgefpDot             -- page 304
  | VcmpgtfpDot             -- page 329
  | VcmpgtsbDot             -- page 330
  | VcmpgtsdDot             -- page 305
  | VcmpgtshDot             -- page 305
  | VcmpgtswDot             -- page 306
  | VcmpgtubDot             -- page 306
  | VcmpgtudDot             -- page 307
  | VcmpgtuhDot             -- page 307
  | VcmpgtuwDot             -- page 308
  | VcmpnebDot              -- page 308
  | VcmpnehDot              -- page 309
  | VcmpnewDot              -- page 310
  | VcmpnezbDot             -- page 311
  | VcmpnezhDot             -- page 309
  | VcmpnezwDot             -- page 310
  | Vctsxs                  -- page 311
  | Vctuxs                  -- page 324
  | Vctzb                   -- page 324
  | Vctzd                   -- page 341
  | Vctzh                   -- page 341
  | Vctzlsbb                -- page 341
  | Vctzw                   -- page 342
  | Veqv                    -- page 341
  | Vexptefp                -- page 312
  | Vextractd               -- page 331
  | Vextractub              -- page 267
  | Vextractuh              -- page 267
  | Vextractuw              -- page 267
  | Vextsb2d                -- page 267
  | Vextsb2w                -- page 294
  | Vextsh2d                -- page 294
  | Vextsh2w                -- page 294
  | Vextsw2d                -- page 294
  | Vextublx                -- page 294
  | Vextubrx                -- page 343
  | Vextuhlx                -- page 343
  | Vextuhrx                -- page 343
  | Vextuwlx                -- page 343
  | Vextuwrx                -- page 344
  | Vgbbd                   -- page 344
  | Vinsertb                -- page 339
  | Vinsertd                -- page 268
  | Vinserth                -- page 268
  | Vinsertw                -- page 268
  | Vlogefp                 -- page 268
  | Vmaddfp                 -- page 331
  | Vmaxfp                  -- page 322
  | Vmaxsb                  -- page 323
  | Vmaxsd                  -- page 299
  | Vmaxsh                  -- page 299
  | Vmaxsw                  -- page 300
  | Vmaxub                  -- page 300
  | Vmaxud                  -- page 299
  | Vmaxuh                  -- page 299
  | Vmaxuw                  -- page 300
  | Vmhaddshs               -- page 300
  | Vmhraddshs              -- page 285
  | Vminfp                  -- page 285
  | Vminsb                  -- page 323
  | Vminsd                  -- page 301
  | Vminsh                  -- page 301
  | Vminsw                  -- page 302
  | Vminub                  -- page 302
  | Vminud                  -- page 301
  | Vminuh                  -- page 301
  | Vminuw                  -- page 302
  | Vmladduhm               -- page 302
  | Vmrgew                  -- page 286
  | Vmrghb                  -- page 257
  | Vmrghh                  -- page 255
  | Vmrghw                  -- page 255
  | Vmrglb                  -- page 256
  | Vmrglh                  -- page 255
  | Vmrglw                  -- page 255
  | Vmrgow                  -- page 256
  | Vmsummbm                -- page 257
  | Vmsumshm                -- page 287
  | Vmsumshs                -- page 287
  | Vmsumubm                -- page 288
  | Vmsumudm                -- page 286
  | Vmsumuhm                -- page 289
  | Vmsumuhs                -- page 288
  | Vmul10cuq               -- page 289
  | Vmul10ecuq              -- page 355
  | Vmul10euq               -- page 355
  | Vmul10uq                -- page 355
  | Vmulesb                 -- page 355
  | Vmulesh                 -- page 281
  | Vmulesw                 -- page 282
  | Vmuleub                 -- page 283
  | Vmuleuh                 -- page 281
  | Vmuleuw                 -- page 282
  | Vmulosb                 -- page 283
  | Vmulosh                 -- page 281
  | Vmulosw                 -- page 282
  | Vmuloub                 -- page 283
  | Vmulouh                 -- page 281
  | Vmulouw                 -- page 282
  | Vmuluwm                 -- page 283
  | Vnand                   -- page 284
  | Vncipher                -- page 312
  | Vncipherlast            -- page 334
  | Vnegd                   -- page 334
  | Vnegw                   -- page 293
  | Vnmsubfp                -- page 293
  | Vnor                    -- page 322
  | Vor                     -- page 313
  | Vorc                    -- page 313
  | Vpermxor                -- page 313
  | Vpkpx                   -- page 338
  | Vpksdss                 -- page 248
  | Vpksdus                 -- page 248
  | Vpkshss                 -- page 249
  | Vpkshus                 -- page 249
  | Vpkswss                 -- page 250
  | Vpkswus                 -- page 250
  | Vpkudum                 -- page 251
  | Vpkudus                 -- page 251
  | Vpkuhum                 -- page 251
  | Vpkuhus                 -- page 251
  | Vpkuwum                 -- page 252
  | Vpkuwus                 -- page 252
  | Vpmsumb                 -- page 252
  | Vpmsumd                 -- page 336
  | Vpmsumh                 -- page 336
  | Vpmsumw                 -- page 337
  | Vpopcntb                -- page 337
  | Vpopcntd                -- page 345
  | Vpopcnth                -- page 345
  | Vpopcntw                -- page 345
  | Vprtybd                 -- page 345
  | Vprtybq                 -- page 314
  | Vprtybw                 -- page 314
  | Vrefp                   -- page 314
  | Vrfim                   -- page 332
  | Vrfin                   -- page 326
  | Vrfip                   -- page 326
  | Vrfiz                   -- page 326
  | Vrlb                    -- page 327
  | Vrld                    -- page 315
  | Vrldmi                  -- page 315
  | Vrldnm                  -- page 320
  | Vrlh                    -- page 320
  | Vrlw                    -- page 315
  | Vrlwmi                  -- page 315
  | Vrlwnm                  -- page 319
  | Vrsqrtefp               -- page 319
  | Vsbox                   -- page 332
  | Vshasigmad              -- page 334
  | Vshasigmaw              -- page 335
  | Vsl                     -- page 335
  | Vslb                    -- page 264
  | Vsld                    -- page 316
  | Vsldoi                  -- page 316
  | Vslh                    -- page 263
  | Vslo                    -- page 316
  | Vslv                    -- page 264
  | Vslw                    -- page 265
  | Vspltb                  -- page 316
  | Vsplth                  -- page 258
  | Vspltisb                -- page 258
  | Vspltish                -- page 259
  | Vspltisw                -- page 259
  | Vspltw                  -- page 259
  | Vsr                     -- page 258
  | Vsrab                   -- page 264
  | Vsrad                   -- page 318
  | Vsrah                   -- page 318
  | Vsraw                   -- page 318
  | Vsrb                    -- page 318
  | Vsrd                    -- page 317
  | Vsrh                    -- page 317
  | Vsro                    -- page 317
  | Vsrv                    -- page 264
  | Vsrw                    -- page 265
  | Vsubcuq                 -- page 317
  | Vsubcuw                 -- page 279
  | Vsubfp                  -- page 275
  | Vsubsbs                 -- page 321
  | Vsubshs                 -- page 275
  | Vsubsws                 -- page 275
  | Vsububm                 -- page 276
  | Vsububs                 -- page 277
  | Vsubudm                 -- page 278
  | Vsubuhm                 -- page 277
  | Vsubuhs                 -- page 277
  | Vsubuqm                 -- page 278
  | Vsubuwm                 -- page 279
  | Vsubuws                 -- page 277
  | Vsum2sws                -- page 278
  | Vsum4sbs                -- page 290
  | Vsum4shs                -- page 291
  | Vsum4ubs                -- page 291
  | Vsumsws                 -- page 292
  | Vupkhpx                 -- page 290
  | Vupkhsb                 -- page 253
  | Vupkhsh                 -- page 254
  | Vupkhsw                 -- page 254
  | Vupklpx                 -- page 254
  | Vupklsb                 -- page 253
  | Vupklsh                 -- page 254
  | Vupklsw                 -- page 254
  | Vxor                    -- page 254
  | Wait                    -- page 313
  | Xnop                    -- page 876
  | XorDot                  -- page 93
  | Xori                    -- page 94
  | Xoris                   -- page 93
  | Xsabsdp                 -- page 93
  | Xsabsqp                 -- page 512
  | Xsadddp                 -- page 512
  | Xsaddsp                 -- page 513
  | Xscmpexpdp              -- page 518
  | Xscmpexpqp              -- page 522
  | Xscmpodp                -- page 523
  | Xscmpudp                -- page 527
  | Xscmpuqp                -- page 530
  | Xscpsgndp               -- page 532
  | Xscpsgnqp               -- page 533
  | Xscvdphp                -- page 533
  | Xscvdpqp                -- page 534
  | Xscvdpsp                -- page 535
  | Xscvdpspn               -- page 536
  | Xscvdpsxds              -- page 537
  | Xscvdpsxws              -- page 537
  | Xscvdpuxds              -- page 540
  | Xscvdpuxws              -- page 542
  | Xscvhpdp                -- page 544
  | XscvqpdpFlagO           -- page 546
  | Xscvqpsdz               -- page 547
  | Xscvqpswz               -- page 548
  | Xscvqpudz               -- page 550
  | Xscvqpuwz               -- page 552
  | Xscvsdqp                -- page 554
  | Xscvspdp                -- page 556
  | Xscvspdpn               -- page 557
  | Xscvsxddp               -- page 558
  | Xscvsxdsp               -- page 559
  | Xscvudqp                -- page 559
  | Xscvuxddp               -- page 560
  | Xscvuxdsp               -- page 561
  | Xsdivdp                 -- page 561
  | Xsdivsp                 -- page 562
  | Xsiexpdp                -- page 566
  | Xsiexpqp                -- page 568
  | Xsmaxdp                 -- page 569
  | Xsmindp                 -- page 579
  | Xsmuldp                 -- page 585
  | Xsmulsp                 -- page 600
  | Xsnabsdp                -- page 604
  | Xsnabsqp                -- page 606
  | Xsnegdp                 -- page 606
  | Xsnegqp                 -- page 607
  | Xsrdpi                  -- page 607
  | Xsrdpic                 -- page 628
  | Xsrdpim                 -- page 629
  | Xsrdpip                 -- page 630
  | Xsrdpiz                 -- page 630
  | Xsredp                  -- page 631
  | Xsresp                  -- page 632
  | XsrqpiFlagInExact       -- page 633
  | Xsrqpxp                 -- page 634
  | Xsrsp                   -- page 636
  | Xsrsqrtedp              -- page 638
  | Xsrsqrtesp              -- page 639
  | Xssqrtdp                -- page 640
  | XssqrtqpFlagO           -- page 641
  | Xssqrtsp                -- page 642
  | Xssubdp                 -- page 644
  | Xssubsp                 -- page 645
  | Xstdivdp                -- page 649
  | Xstsqrtdp               -- page 651
  | Xststdcdp               -- page 652
  | Xststdcqp               -- page 653
  | Xststdcsp               -- page 654
  | Xsxexpdp                -- page 655
  | Xsxexpqp                -- page 656
  | Xsxsigdp                -- page 656
  | Xsxsigqp                -- page 657
  | Xvabsdp                 -- page 657
  | Xvabssp                 -- page 658
  | Xvadddp                 -- page 658
  | Xvaddsp                 -- page 659
  | XvcmpeqdpDot            -- page 663
  | XvcmpeqspDot            -- page 665
  | XvcmpgedpDot            -- page 666
  | XvcmpgespDot            -- page 667
  | XvcmpgtdpDot            -- page 668
  | XvcmpgtspDot            -- page 669
  | Xvcpsgndp               -- page 670
  | Xvcpsgnsp               -- page 671
  | Xvcvdpsp                -- page 671
  | Xvcvdpsxds              -- page 672
  | Xvcvdpsxws              -- page 673
  | Xvcvdpuxds              -- page 675
  | Xvcvdpuxws              -- page 677
  | Xvcvhpsp                -- page 679
  | Xvcvspdp                -- page 681
  | Xvcvsphp                -- page 682
  | Xvcvspsxds              -- page 683
  | Xvcvspsxws              -- page 684
  | Xvcvspuxds              -- page 686
  | Xvcvspuxws              -- page 688
  | Xvcvsxddp               -- page 690
  | Xvcvsxdsp               -- page 692
  | Xvcvsxwdp               -- page 692
  | Xvcvsxwsp               -- page 693
  | Xvcvuxddp               -- page 693
  | Xvcvuxdsp               -- page 694
  | Xvcvuxwdp               -- page 694
  | Xvcvuxwsp               -- page 695
  | Xvdivdp                 -- page 695
  | Xvdivsp                 -- page 696
  | Xviexpdp                -- page 698
  | Xviexpsp                -- page 700
  | Xvmaddmdp               -- page 700
  | Xvmaxdp                 -- page 701
  | Xvmaxsp                 -- page 707
  | Xvmindp                 -- page 709
  | Xvminsp                 -- page 711
  | Xvmsubmsp               -- page 713
  | Xvmuldp                 -- page 718
  | Xvmulsp                 -- page 721
  | Xvnabsdp                -- page 723
  | Xvnabssp                -- page 725
  | Xvnegdp                 -- page 725
  | Xvnegsp                 -- page 726
  | Xvrdpi                  -- page 726
  | Xvrdpic                 -- page 741
  | Xvrdpim                 -- page 741
  | Xvrdpip                 -- page 742
  | Xvrdpiz                 -- page 742
  | Xvredp                  -- page 743
  | Xvresp                  -- page 744
  | Xvrspi                  -- page 745
  | Xvrspic                 -- page 746
  | Xvrspim                 -- page 746
  | Xvrspip                 -- page 747
  | Xvrspiz                 -- page 747
  | Xvrsqrtedp              -- page 748
  | Xvrsqrtesp              -- page 748
  | Xvsqrtdp                -- page 750
  | Xvsqrtsp                -- page 751
  | Xvsubdp                 -- page 752
  | Xvsubsp                 -- page 753
  | Xvtdivdp                -- page 755
  | Xvtdivsp                -- page 757
  | Xvtsqrtdp               -- page 758
  | Xvtsqrtsp               -- page 759
  | Xvtstdcdp               -- page 759
  | Xvtstdcsp               -- page 760
  | Xvxexpdp                -- page 761
  | Xvxexpsp                -- page 762
  | Xvxsigdp                -- page 762
  | Xvxsigsp                -- page 763
  | Xxbrd                   -- page 763
  | Xxbrh                   -- page 764
  | Xxbrq                   -- page 764
  | Xxbrw                   -- page 765
  | Xxextractuw             -- page 765
  | Xxinsertw               -- page 766
  | Xxland                  -- page 766
  | Xxlandc                 -- page 767
  | Xxleqv                  -- page 767
  | Xxlnand                 -- page 768
  | Xxlnor                  -- page 768
  | Xxlor                   -- page 769
  | Xxlorc                  -- page 770
  | Xxlxor                  -- page 769
  | Xxmrghw                 -- page 770
  | Xxmrglw                 -- page 771
  | Xxpermdi                -- page 771
  | Xxsldwi                 -- page 773
  | Xxspltib                -- page 774
  | Xxspltw                 -- page 774
  deriving (Generic, Show, Eq, NFDataX)